### PR TITLE
Fix long tag display

### LINKED ISSUE #616: Display issues when using very long tag names
As seen here: https://github.com/padloc/padloc/discussions/615

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Fixes #616

I didn't implement the limit on input because the only time people complained about long names was with automatic imports, which wouldn't be fixed by that new limitation.

I also tried adding a tooltip, but failed, and in the end, clicking on the item allows viewing the tag without it being truncated, so it should be fine.

Screenshot from 2022-11-25 15-07-11

### CODE REVIEW

File: packages/app/src/styles/misc.ts [hunk 1]
```diff
@@ -64,6 +64,10 @@ export const misc = css`
         color: var(--color-negative);
     }
 
+    .tag.ellipsis {
+        max-width: 100px;
+    }
+
```
Comment (MaKleSoft) [inline packages/app/src/styles/misc.ts:70]: I think this rule is much too broad. Can we add this [here](https://github.com/padloc/padloc/blob/main/packages/app/src/elements/items-list.ts#L163) instead? Also, please try to use `em` as sizing units wherever possible.

**Review by MaKleSoft — CHANGES_REQUESTED** [review]

File: packages/app/src/styles/misc.ts (hunk 1 above)
Comment (BrunoBernardino) [reply packages/app/src/styles/misc.ts]: Done.

**Review by MaKleSoft — APPROVED** [review]
